from typing import Optional
from models import *
from fastapi import FastAPI, HTTPException, status
from pydantic import *
from schemas import *

# Command to initialize server
# uvicorn main:app --reload

# Documentation and manual testing (generated by FastAPI):
# http://localhost:8000/docs

app = FastAPI()


@app.get("/")
async def readRoot():
    return "Hello World"


@app.get("/game/")
async def get_game_list():
    with db_session:
        gamesList = Game.select()
        response = [GameInDB.from_orm(p) for p in gamesList]
    return response


@app.post("/game/", response_model=GameOUT, status_code=status.HTTP_201_CREATED)
async def create_game(newGame: GameIN):
    with db_session:
        Game(name=newGame.name)
    return GameOUT(name=newGame.name, operationResult="Succesfully created!")
